#! /usr/bin/env bash

if [ $# -ne 1 ]
then
  echo "missing name of ts file" && exit 1
fi
DST="$HOME/.cache/gstate"
[ ! -d "$DST" ] && mkdir "$DST"
FILE="$DST/$1"
[ -r "$FILE" ] || touch "$FILE"
A=$(stat -c %X "$FILE")
C=$(date +%s)
D=$(( (C - A) / (60*60*24) ))
echo "last GC : $D"
[ $D -gt 15 ] && git gc && rm "$FILE" && touch "$FILE"
date > "$FILE"
