#! /usr/bin/env ruby
# frozen_string_literal: true

require 'json'

before = JSON.parse($stdin.gets.chomp)
after = $stdin.gets.chomp
_args = ARGV[1]
cmd = ARGV[2]
data = ARGV[4].split(':')[1]

note = before['note']
if note.nil? || note == 'NO' || !File.exist?(note)
  puts after
  exit(0)
end

require 'fileutils'

if cmd == 'delete'
  FileUtils.unlink(before['note'])
  puts after
  exit(0)
end

task = JSON.parse(after)
uuid = task['uuid']
prj = task['project'] || ''

start = task['start']
unless start.nil?
  system("sed -i 's/\\[START\\]/[#{start}]/' #{task['note']}")
  task['note'] = File.join(data, 'notes', prj, 'active', "#{uuid}.md")
end

done = task['end']
unless done.nil?
  system("sed -i 's/\\[COMPLETION\\]/[#{done}]/' #{task['note']}")
  task['note'] = File.join(data, 'notes', prj, 'done', "#{uuid}.md")
end

if note != task['note']
  note_dir = File.dirname(task['note'])
  FileUtils.mkdir_p(note_dir)
  FileUtils.mv(before['note'], task['note'])
end

puts task.to_json
