-- ORACLE_PATH=./config/oracle
SET PAGESIZE 0
SET NEWPAGE 0
SET SPACE 0
SET LINESIZE 1000
SET ECHO OFF
SET FEEDBACK OFF
SET HEADING OFF
SET VERIFY OFF
SET MARKUP HTML OFF SPOOL OFF
SET COLSEP ","
SET TAB OFF
SET TRIMSPOOL ON
