#! /usr/bin/bash

rm -rf ~/.cache/nvim
rm -rf ~/.cache/jdtls
rm -rf ~/.config/nvim
rm -rf ~/.local/state/nvim

mkdir -p ~/.config/nvim
cd ~/.config/nvim
ln -s ~/usr/dotfiles/nvim/lua
ln -s ~/usr/dotfiles/nvim/init.lua
