#! /usr/bin/env bash

RESET="\033[0m"
RED="\033[0;31m"

function fail()
{
  echo -e "$RED error$RESET: $1" && exit 1
}

function say()
{
  echo -e "$RED:: $RESET$1"
}

[ $UID -ne 0 ] && fail "must be run as root"
[ $# -ne 1 ] && fail "missing user"

USR=$1
USRH=/home/$USR
HOSTNAME=$(uname -n)
ELIST=arch-bkp-files-etc
HLIST=arch-bkp-files-home

[ -d "$USRH" ] || fail "$USRH is not avalid user directory"
[ -r "$ELIST" ] || fail "missing file : $ELIST"
[ -r "$HLIST" ] || fail "missing file : $HLIST"

PKGS=/tmp/${HOSTNAME}-packages
GEMS=/tmp/${HOSTNAME}-gems
HRDW=/tmp/${HOSTNAME}-hardware
SRVS=/tmp/${HOSTNAME}-services
LIST=/tmp/${HOSTNAME}-list
TGZ=$USRH/${HOSTNAME}-archive.tgz

function cl() {
  [ -e "$PKGS" ] && rm "$PKGS"
  [ -e "$GEMS" ] && rm "$GEMS"
  [ -e "$HRDW" ] && rm "$HRDW"
  [ -e "$SRVS" ] && rm "$SRVS"
  [ -e "$LIST" ] && rm "$LIST"
}

cl
say "generate package list $PKGS ..."
pacman -Q > "$PKGS"
say "generate gem list $GEMS ..."
gem list > "$GEMS"
say "generate hardware list $HRDW ..."
lspci -tv > "$HRDW"
lsusb -t >> "$HRDW"
say "generate services list $SRVS ..."
systemctl --type=service --state=active | grep service > "$SRVS"
say "archive etc ..."
{
  cat $ELIST | while read -r name; do test -r "$name" && echo "$name"; done
  find /etc/systemd/system/ -type f
  find /etc/systemd/network/ -type f
  find /etc/systemd/user/ -type f
  cat $HLIST | while read -r name; do test -r "$USRH/$name" && echo "$USRH/$name"; done
  echo "$PKGS"
  echo "$GEMS"
  echo "$HRDW"
  echo "$SRVS"
} > "$LIST"
sed -i 's#^/##' "$LIST"
say "generate $TGZ"
tar -czpf "$TGZ" -C / -T "$LIST" || fail "tar failure" # -h to follow symlinks
chown "$USR" "$TGZ"
cl
say "hardcore restore : sudo tar --same-owner -xzf $(basename "$TGZ") -C /"
