#! /usr/bin/env bash

# PROMPT
function parse_git_branch()
{
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}
export PS1='\[\033[01;33m\]\u\[\033[01;35m\]@\[\033[00;31m\]\h\[\033[00m\]:\[\033[0;33m\] \W \[\033[01;35m\]$(parse_git_branch)\[\033[0;33m\] \[\033[0m\]\$ '
unset PROMPT_COMMAND

# DPI
export QT_FONT_DPI=100
export QT_SCALE_FACTOR=1

# ENV
export PATH=${HOME}/bin:${PATH#"${HOME}/bin:"}
export TERM='xterm-256color'
export EDITOR=nvim
export GEM_HOME="${HOME}/.gem/ruby/3.3.0"
export PATH=$PATH:$GEM_HOME/bin
export MPD_HOST=fakenews
export XDG_CONFIG_HOME="$HOME/.config"
export ORACLE_PATH="$HOME/.config/oracle"
export GPG_TTY=$(tty) # pinentry
export JDTLS_JVM_ARGS="$HOME/.local/share/nvim/mason/packages/jdtls/lombok.jar"

# shellcheck source=/dev/null
[ -r "$HOME/.config/local/bash.sh" ] && source "$HOME/.config/local/bash.sh"

# ZOXIDE
export _ZO_ECHO=1
eval "$(zoxide init --cmd cd bash)"

# LS COLORS
[ -r ~/.dir_colors ] && eval "$(dircolors ~/.dir_colors)"
alias ls="ls --color=auto -F -b -T 0"
alias la="ls -l --color=auto -F -b -T 0"

# BELL
[ -n "$DISPLAY" ] && xset b 0

# VIMMODE
set -o vi

# catch and eval dmalloc output
#function dmalloc { eval `command dmalloc -b $*`; }
alias mutt=neomutt
alias cat=bat
alias vim=nvim
alias v="nvim ."
alias vimdiff="nvim -d"
alias gvim='nvim --listen godothost .'
alias tt='clear && task'
alias ddu='zcat ~/.cache/ncdu-data.gz | ncdu -f-'
# alias fuck='eval $(thefuck $(fc -ln -1)); history -r'
# alias sf='systemctl --user restart pipewire*'
# alias kk='khal calendar'
# alias ki='khal interactive'
# alias zz='clear && khal calendar && task -old'
# alias cc='cd $(find ~/usr ~/_wip -type d | fzy)'
# alias cl='clean .'

# FUNCTIONS
function lip () {    # local ips
    ip -4 -c addr | sed -n '/^[1-9]:/p;/inet/p'
}

function xip () {    # external ip
    dig +short myip.opendns.com @resolver1.opendns.com
}

function rman () {   # centered man
    env COLUMNS=$((COLUMNS*2/3)) man "${@}" | pr -o $((COLUMNS/2/3)) | less
}

function xcon () {   # external established connections
    ss -t -o state established '( dport = :443 || dport = :80  )' \
        | grep -Po '([0-9a-z:.]*)(?=:http[s])' | sort -u  \
        | netcat whois.cymru.com 43 | grep -v "AS Name" | sort -t'|' -k3
}

function tm()
{
  if [ $# -eq 0 ]
  then
    tmux new-session \; source-file -q ./tmux.conf \;
  else
    local session=$1
    tmux a -t "$session" && return
    if [ -r "$HOME/.config/tmux/sessions/$session.conf" ]
    then
      tmux new-session \; source-file "$HOME/.config/tmux/sessions/$session.conf" \;
    else
      cd "$session" && tmux new-session \; source-file -q ./tmux.conf \;
    fi
  fi
}

# SSH AGENT
if ! (ssh-add -l &>/dev/null)
then
    [ -r ~/.ssh/agent ] && eval "$(<~/.ssh/agent)" >/dev/null
    if ! (ssh-add -l &>/dev/null)
    then
        (umask 066; ssh-agent > ~/.ssh/agent)
        eval "$(<~/.ssh/agent)" >/dev/null
    fi
fi

[ -r "$HOME/.bash_local" ] && "$HOME/.bash_local"
