#! /usr/bin/env bash

cd ~/_wip || exit 1
source "clean.cfg" || exit 1

for dir in "${dirs[@]}"
do
  path=${clean_args["$dir",0]}
  cmd=${clean_args["$dir",1]}
  echo "clean $path" && pushd "$path" > /dev/null && $cmd > /dev/null && popd > /dev/null
done
