#! /usr/bin/env bash

#-profile profile.9.cfg"
# -locked -profile profile.9.cfg"
WMNG=/opt/efl/bin/enlightenment_start
# WMNG=fluxbox

${WIN:-$WMNG} & PID=$!

# needs xdg-desktop-portal-gtk
dbus-update-activation-environment --systemd DISPLAY XDG_CURRENT_DESKTOP=GTK GDK_DPI_SCALE=1.8

# toooo annaying
# if [ "$(which xkblayout-state 2>/dev/null)" ]
# then
#   sleep 1
#   if [ "$(xkblayout-state print '%s')" = "ch" ]
#   then
#     setxkbmap -option ctrl:swapcaps
#   else
#     setxkbmap -option
#   fi
# fi

wait ${PID}
